Initial commit

diff --git a/freecsD b/freecsD
--- a/freecsD
+++ b/freecsD
@@ -1,11 +1,11 @@
 #!/bin/sh
 
-script_revision=74
-script_name=freecsD
-script_download=http://progettofreecs.altervista.org/download/freecsD/freecsD
+script_revision=65
+script_name=freecsD.unstable
+script_download=http://progettofreecs.altervista.org/download/freecsD/freecsD.unstable
 
 ## aggiungere altri path separati solo da una virgola ","
-configdir_array="/winfreecsD/oscam/cygwin-dlls,/usr/keys/oscam_atv_ymod,/usr/keys/oscam_atv_emu,/etc/oscam,/etc/tuxbox/config/oscam,/usr/keys/oscam_atv,/etc/tuxbox/config,/usr/local/oscam-svn/Distribution/config,/etc/oscam-svn,/usr/local/etc,/storage/.xbmc/userdata/addon_data/service.softcam.oscam/config,/storage/.kodi/userdata/addon_data/service.softcam.oscam/config,/usr/local/oscam/var,/usr/keys/oscam_emu,/usr/config/OScam,/var/tuxbox/config,/usr/local/etc/oscam1,/usr/keys,/usr/keys/oscam"
+configdir_array="/usr/keys/oscam_atv_emu,/etc/oscam,/etc/tuxbox/config/oscam,/usr/keys/oscam_atv,/etc/tuxbox/config,/usr/local/oscam-svn/Distribution/config,/etc/oscam-svn,/usr/local/etc,/storage/.xbmc/userdata/addon_data/service.softcam.oscam/config,/storage/.kodi/userdata/addon_data/service.softcam.oscam/config,/usr/local/oscam/var,/usr/keys/oscam_emu,/usr/config/OScam,/var/tuxbox/config,/usr/local/etc/oscam1,/usr/keys,/usr/keys/oscam"
 
 noupdate_time=3600 ## Se l'ultima richiesta cline è stata effettuata meno di 1 ora (3600 secondi) fa la ignora
 monitor_time=3600 ## Se un server down 1 ora lo disabilito
@@ -14,13 +14,9 @@ check_interval=180 ## secondi prima di riavviare l'handler
 tempdir=/tmp
 agent="Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7|Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36|Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36|Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36|Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36|Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0|Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
 agent=$(echo $agent | cut -d'|' -f$(($(echo $(date '+%s') % 10)+1)))
-# patch per windows
-os_windows=$(uname -a|grep -i "windows")
 
 server_list="http://progettofreecs.altervista.org/download/freecsD/servers"
 server_list_unstable="http://progettofreecs.altervista.org/download/freecsD/servers_unstable"
-#server_list_orator="http://poetanovus.altervista.org/FreecsD/servers"
-#server_list_unstable_orator="http://poetanovus.altervista.org/FreecsD/servers_unstable"
 server_list_file="$tempdir/servers"
 upload_url="http://progettofreecs.altervista.org/save_list.php"
 #############################################################################################
@@ -89,70 +85,6 @@ helpme () {
     exit 0
 }
 
-# $1=internal $2=url $3=cookie $4=referer $5=redirect $6=data $7=uagent
-igen () {
-  gen_data=$(echo "$1" | cut '-d ' -f6)
-  url_cookie=$(echo "$1" | cut '-d ' -f3)
-  if [ ! -z "$(echo $url_cookie | grep "^0$")" ]; then
-    url_cookie=
-  fi
-  url_referer=$(echo "$1" | cut '-d ' -f4)
-  if [ ! -z "$(echo $url_referer | grep "^0$")" ]; then
-    url_referer=
-  fi
-  gen_uagent=$(echo "$1" | cut '-d ' -f7-)
-  url_location=$(echo "$1" | cut '-d ' -f2)
-  url_redirect=$(echo "$1" | cut '-d ' -f5)
-  debug "url_location=$url_location"
-  url_domain=$(echo "$url_location" | awk -F// '{print $2}' | cut -d "'" -f1 | cut -d / -f1)
-
-  debug "url_domain=$url_domain"
-  debug "gen_uagent=$gen_uagent"
-
-  if [ -z "$(echo $url_redirect | grep "^0$")" ]; then
-    verbose "Ottengo dati dal server $url_domain"
-    therequest="GET $url_location HTTP/1.1\r\nHost: $url_domain\r\nUser-Agent: $gen_uagent\r\n"
-    if [ ! -z "$url_cookie" ]; then
-      therequest="$therequest""Cookie: $url_cookie\r\n"
-    fi
-    if [ ! -z "$url_referer" ]; then
-      therequest="$therequest""Referer: $url_referer\r\n"
-    fi
-    therequest="$therequest\r\n"
-    therequest=$(echo -ne $therequest | nc $url_domain 80)
-    t=$(echo "$therequest" | grep Set-Cookie | cut '-d ' -f2)
-    if [ ! -z "$t" ]; then
-      url_cookie=$t
-    fi
-    debug "$therequest"
-    debug "Cookie: $url_cookie"
-    t=$(echo "$therequest" | grep Referer | cut '-d ' -f2)
-    if [ ! -z "$t" ]; then
-      url_referer=$t
-    fi
-    debug "Referer: $url_referer"
-    t=$(echo "$therequest" | grep Location | cut '-d ' -f2)
-    if [ ! -z "$t" ]; then
-      url_location=$t
-    fi
-    debug "Location: $url_location"
-  fi
-    therequest="POST $url_location HTTP/1.1\r\nHost: $url_domain\r\nUser-Agent: $gen_uagent\r\nConnection: keep-alive\r\n"
-    if [ ! -z "$url_cookie" ]; then
-      therequest="$therequest""Cookie: $url_cookie\r\n"
-    fi
-    if [ ! -z "$url_referer" ]; then
-      therequest="$therequest""Referer: $url_referer\r\n"
-    fi
-    if [ ! -z "$gen_data" ]; then
-      therequest="$therequest""Content-Type: application/x-www-form-urlencoded\r\nContent-Length: ${#gen_data}\r\n\r\n$gen_data"
-    else
-      therequest="$therequest\r\n"
-    fi
-    verbose "Ricevo i dati da $gen_url"
-    echo "$(echo -e $therequest | nc -i3 $url_domain 80)"
-}
-
 #############################################################################################
 
 # incrementa group id
@@ -169,7 +101,7 @@ sort_start="1"
 tor_flag=
 tor_patch_flag=
 
-args="ach0siP:T:UVL:S:I:n:l:t:o:x:y:z:"
+args="ach0siPTUVL:S:I:n:l:t:o:x:y:z:"
 
 case "$1" in
 -h|helpme)
@@ -227,11 +159,9 @@ while getopts $args opt; do
     V)  echo $script_revision; exit 0 ;;
     L)  upload_flag="true"; upload_file="curl -F uploadedfile=@$OPTARG $upload_url" ;;
     T)  tor_flag="true";
-        clines_for_tor="$OPTARG"
+        echo "" > "/tmp/clines-for-tor"
         ;;
-    P)  tor_patch_flag="true"
-        clines_for_tor="$OPTARG"
-        ;;
+    P)  tor_patch_flag="true" ;;
     S)  sort_flag="true"; sort_start="$OPTARG";
         if echo "$sort_start" | grep -qE ^\-?[[:digit:]]+$; then
            debug "Riassegno i gruppi a partire da $sort_start"
@@ -251,22 +181,13 @@ fi
 
 if [ ! -z $upgrade_flag ]; then
   curl -k -L -s "$script_download" > "$tempdir/$script_name"
-  # patch per windows
-  if [ -z "$os_windows" ]; then
-    chmod +x "$tempdir/$script_name"
-  fi
+  chmod +x "$tempdir/$script_name"
   old=$("$0" -V)
   new=$("$tempdir/$script_name" -V)
   debug "Versione installata: $old  -  Versione scaricata: $new"
   if [ "$old" -lt "$new" ]; then
-    # patch per windows
-    if [ -z "$os_windows" ]; then
-      verbose "Aggiorno $0 alla revisione $new"
-      mv "$tempdir/$script_name" "$0"
-    else
-      verbose "Versione installata: $old  -  Versione scaricata: $new"
-      verbose "Impossibile aggiornare freecsD: eseguire freecsD-U (senza spazio!) per aggiornare."
-    fi
+    verbose "Aggiorno $0 alla revisione $new"
+    mv "$tempdir/$script_name" "$0"
   else
     verbose "Non aggiornato: $0 è alla revisione $old, la più recente."
     rm "$tempdir/$script_name"
@@ -310,10 +231,6 @@ if [ -z "$oscam_ip" ]; then
     error "Non è stato possibile leggere la porta della WebIf"
 fi
 oscam_logfile=$(sed -n 's/^ *logfile *= *//p' "$oscam_configdir/oscam.conf")
-# patch per windows
-if [ ! -z "$os_windows" ]; then
-    oscam_logfile="/winfreecsD/oscam/cygwin-dlls/tmp/oscam.log"
-fi
 if [ -z "$oscam_logfile" ]; then
     error "Non è stato possibile trovare il path di oscam.log"
 fi
@@ -368,7 +285,7 @@ if [ -z "$tor_flag" ]; then
 else
     verbose "torpatch: preparo per secondo passaggio"
     debug "torpatch: '$1' '$page'"
-    echo "$1|$page" >> "$clines_for_tor"
+    echo "$1|$page" >> "/tmp/clines-for-tor"
 fi
 }
 add_reader () { # add_reader label
@@ -426,21 +343,14 @@ parse_execute_command () {
         parsed_command=$(echo "$parsed_command" | sed "s|#uagent#|$agent|g")
     fi
     debug "Eseguo.. '$parsed_command'"
-    if [ -z "$(echo $parsed_command | grep '^internal ')" ];then
-       execute_result=$(eval $parsed_command)
-    else
-       execute_result=$(igen "$parsed_command")
-    fi
+    execute_result=$($parsed_command)
 
    ##############C:-ALMENO 1 SPAZIO-#----------------------DOMINIO-----------------------------#-ALMENO 1 SPAZIO-#PORTA ALM 2 NUM#-ALMENO 1 SPAZIO-#--------USERNAME---------#-ALMENO 1 SPAZIO-#--------PASSWORD---------#
 	clinepattern="[Cc]:[[:blank:]]\{1,\}\([[:alnum:]][-.]*\)*\([[:alnum:]]\)*.\([[:alpha:]]\{2,6\}\)[[:blank:]]\{1,\}[[:digit:]]\{2,\}[[:blank:]]\{1,\}\([[:alnum:]][-.,/]*\)\{1,\}[[:blank:]]\{1,\}\([[:alnum:]][-.,/]*\)\{1,\}"
 	clines=$(echo "$execute_result" | sed "s/$clinepattern/&\
 /g" | sed -n "s/.*\($clinepattern\).*/\1/p")
     if [ ! -z "$clines" ]; then
-        # patch per windows
-#        echo "$clines" | while read cline
-        echo "$clines" > /tmp/cl
-        while read cline
+        echo "$clines" | while read cline
          do
 			cline=$(echo "$cline" | sed "s/[[:blank:]]\{1,\}/ /g")
             verbose "Ho Ottenuto '$cline' aggiungo/aggiorno al gruppo '$group'..."
@@ -454,13 +364,9 @@ parse_execute_command () {
                 debug "Il server 'host,$port' risulta disabilitato, lo riabilito e aggiorno i dati."
             fi
                 add_reader "$host,$port"
-                # patch per windows
-                sleep 5
                 webif_request "label=$host,$port&user=$user&password=$password&description=#freecsd $(date '+%s')#$original_command&device=$host,$port&protocol=cccam&enable=$leave_enabled&group=$group&fallback=0&fallback_percaid=&lb_weight=100&caid=&ident=&chid=&localcards=&audisabled=0&auprovid=&ratelimitecm=&ecmunique=0&ratelimittime=&srvidholdtime=&cooldowndelay=&cooldowntime=&ecmnotfoundlimit=&ecmwhitelist=&ecmheaderwhitelist=&dropbadcws=0&disablecrccws=0&emmcache=&saveemm-unknown=0&saveemm-u=0&saveemm-s=0&saveemm-g=0&blockemm-unknown=0&blockemm-u=0&blockemm-s=0&blockemm-g=0&blockemm-bylen=&inactivitytimeout=100&reconnecttimeout=30&cccreconnect=12000&cccversion=2.1.1&cccmaxhops=10&cccmindown=0&cccreshare=-1&cccwantemu=1&ccckeepalive=1&cacheex=0&cacheex_maxhop=0&cacheex_ecm_filter=&cacheex_drop_csp=0&cacheex_allow_request=0&cacheex_allow_filter=1&cacheex_block_fakecws=0&action=Save"
 
-# patch per windows
-#        done
-        done < /tmp/cl
+        done
     else
 	if [ ! -z "$incgroup" ]; then
             group_from=$(($group_from-1))
@@ -469,6 +375,10 @@ parse_execute_command () {
 }
 
 tor_patch_wbr () {
+clines_for_tor=/tmp/clines-for-tor
+if [ ! -z "$1" ]; then
+     clines_for_tor=$1
+fi
 verbose "Elaboro le chiamate alla webif da $clines_for_tor, attendere ..."
 #label=$host,$port&user=
 if [ -f "$clines_for_tor" ]; then
@@ -478,9 +388,9 @@ if [ -f "$clines_for_tor" ]; then
          req=$(echo "$line" | cut '-d|' -f1)
          p=$(echo "$line" | cut '-d|' -f2)
          webif_request "$req" $p
-	 sleep 5
      fi
      done < "$clines_for_tor"
+   rm "$clines_for_tor"
 else
    verbose "Nessuna chiamata presente"
 fi
@@ -490,9 +400,6 @@ fi
 }
 
 handle_servers () {
-#patch onions
-echo "" > /tmp/check.label
-
 if [ ! -z "$(echo "$oscam_disablelog" | grep "^1$")" ]; then
     error "Il log di OSCam è disabilitato!"
 fi
@@ -512,10 +419,7 @@ badloginslabels=$(echo "$cuttedlog" | grep "login failed" | sed "s/$labelpattern
 /g" | sed -n "s/.*\($labelpattern\).*/\1/p" | sed "s/[[:blank:]]//g" | awk '!x[$0]++')
 debug "Lista server con LOGIN FAILED:
 $badloginslabels"
-# patch per windows
-#echo "$badloginslabels" | while read label
-echo "$badloginslabels" > /tmp/bll
-while read label
+echo "$badloginslabels" | while read label
  do
     if [ ! -z "$label" ]; then
         original_description=$(sed -n "/$label/,/^\s*\[/{/^[^;].*\=.*/p;}" "$oscam_server" | sed -n 's/ *description *= *//p')
@@ -539,18 +443,13 @@ while read label
             debug "Il server '$label' sta restituendo login failed ma non appartiene a freecsd"
         fi
     fi
-# patch per windows
-# done
-done < /tmp/bll
+done
 
-connectionfailedlabels=$(echo "$cuttedlog" | grep "init error\|Connection refused\|tion timed out\|reason close" | sed "s/$labelpattern/&\
+connectionfailedlabels=$(echo "$cuttedlog" | grep "Connection refused\|tion timed out\|reason close" | sed "s/$labelpattern/&\
 /g" | sed -n "s/.*\($labelpattern\).*/\1/p" | sed "s/[[:blank:]]//g" | awk '!x[$0]++')
 debug "Lista server con CONNECTION FAILED:
 $connectionfailedlabels"
-# patch per windows
-#echo "$connectionfailedlabels" | while read label
-echo "$connectionfailedlabels" > /tmp/cfl
-while read label
+echo "$connectionfailedlabels" | while read label
  do
     if [ ! -z "$label" ]; then
         original_description=$(sed -n "/$label/,/^\s*\[/{/^[^;].*\=.*/p;}" "$oscam_server" | sed -n 's/ *description *= *//p')
@@ -558,20 +457,11 @@ while read label
             original_command=$(echo "$original_description" | sed "s|#freecsd.*[[:blank:]][[:digit:]]*#||g" | sed "s|&|%26|g")
             lastupdate=$(echo "$original_description" | cut '-d#' -f2 | cut '-d ' -f2)
             lastfail=$(echo "$original_description" | cut '-d#' -f2 | cut '-d ' -f3)
-            # patch per windows
-            if echo "$lastfail" | grep -qE ^\-?[[:digit:]]+$; then
-               debug "Stringa numerica"
-            else
-               debug "Stringa non numerica. La inizializzo."
-               lastfail=""
-            fi
             if [ ! -z "$lastfail" ]; then
         if [ $date_now -gt $check_interval ]; then
             if [ $(($lastfail+$monitor_time)) -lt $date_now ]; then
                 debug "Disabilito '$label', tempo di ripristino di $monitor_time secondi superato"
                 webif_request "label=$label&description=#freecsd $lastupdate $date_now#$original_command&enable=0&action=Save"
-                # patch onions
-                echo "$label" >> /tmp/check.label
             else
                 debug "Lascio attivo '$label', non ancora passati $monitor_time secondi dal primo fail"
             fi
@@ -592,18 +482,13 @@ while read label
             debug "Il server '$label' sta fallendo ma non appartiene a freecsd"
         fi
     fi
-# patch per windows
-# done
-done < /tmp/cfl
+done
 
 alllabels=$(cat "$oscam_server" | sed "s/$labelpattern/&\
 /g" | sed -n "s/.*\($labelpattern\).*/\1/p" | sed "s/[[:blank:]]//g" | awk '!x[$0]++')
 debug "Lista di tutti i server:
 $alllabels"
-# patch per windows
-#echo "$alllabels" | while read label
-echo "$alllabels" > /tmp/al
-while read label
+echo "$alllabels" | while read label
  do
     if [ ! -z "$label" ]; then
         original_description=$(sed -n "/$label/,/^\s*\[/{/^[^;].*\=.*/p;}" "$oscam_server" | sed -n 's/ *description *= *//p')
@@ -612,15 +497,6 @@ while read label
             enabled=$(sed -n "/$label/,/^\s*\[/{/^[^;].*\=.*/p;}" "$oscam_server" | sed -n 's/ *enable *= *//p')
             lastupdate=$(echo "$original_description" | cut '-d#' -f2 | cut '-d ' -f2)
             lastfail=$(echo "$original_description" | cut '-d#' -f2 | cut '-d ' -f3)
-            # patch per windows
-            if echo "$lastfail" | grep -qE ^\-?[[:digit:]]+$; then
-               debug "Stringa numerica"
-            else
-               debug "Stringa non numerica. La inizializzo."
-               lastfail=""
-            fi
-if ! grep "$label" /tmp/check.label; then #patch onions
-
     if [ ! -z "$lastfail"  ]; then
         if [ ! -z "$(echo "$enabled" | grep "^0$")"  ]; then
             if [ $date_now -gt $check_interval ]; then
@@ -647,11 +523,9 @@ if ! grep "$label" /tmp/check.label; then #patch onions
                 webif_request "label=$label&description=#freecsd $date_now#$original_command&action=Save"
             fi
         fi
-
-fi #patch onions
     else
         if [ $date_now -lt $check_interval ]; then
-            debug "Aggiornamento INIZIALE '$label', sostituito last update"
+             debug "Aggiornamento INIZIALE '$label', sostituito last update"
             webif_request "label=$label&description=#freecsd $date_now#$original_command&action=Save"
         fi
     fi
@@ -659,9 +533,7 @@ fi #patch onions
             debug "Il server '$label' non appartiene a freecsd"
         fi
     fi
-# patch per windows
-# done
-done < /tmp/al
+done
 
 debug "Handler Eseguito!"
 }
@@ -716,32 +588,30 @@ if [ ! -z $inizialization_flag ]; then
     else
             verbose "OK! CURL installato"
     fi
-    # patch per windows
-    if [ -z "$os_windows" ]; then
-      processlist=$(ps x 2>&1)
-      if [ $? -gt 0 ]; then
-          processlist=$(ps)
-      fi
 
-      echo $processlist | grep -v grep | grep cron > /dev/null
-      if [ $? -eq 0 ]; then
-        verbose "OK! Cron sembra essere in esecuzione"
-      else
-        verbose "ATTENZIONE! Cron sembra NON essere in esecuzione"
-      fi
+    processlist=$(ps x 2>&1)
+    if [ $? -gt 0 ]; then
+        processlist=$(ps)
+    fi
 
-      fullcrontab=$(crontab -l)
-      fullcmdpath=$(echo $0 | sed "s|\./|$(pwd)/|g")
-      linetoadd="*/6 * * * * $fullcmdpath -s"
-      if [ -z "$(echo -n "$fullcrontab" | grep "$fullcmdpath")"  ]; then
-          verbose "Aggiungo FreecsD al crontab"
-          echo "$fullcrontab" > "$tempdir/mycron"
-          echo "$linetoadd" >> "$tempdir/mycron"
-          crontab "$tempdir/mycron"
-          rm "$tempdir/mycron"
-      else
-          verbose "OK! FreecsD è già presente nel crontab"
-      fi
+    echo $processlist | grep -v grep | grep cron > /dev/null
+    if [ $? -eq 0 ]; then
+      verbose "OK! Cron sembra essere in esecuzione"
+    else
+      verbose "ATTENZIONE! Cron sembra NON essere in esecuzione"
+    fi
+
+    fullcrontab=$(crontab -l)
+    fullcmdpath=$(echo $0 | sed "s|\./|$(pwd)/|g")
+    linetoadd="*/6 * * * * $fullcmdpath -s"
+    if [ -z "$(echo -n "$fullcrontab" | grep "$fullcmdpath")"  ]; then
+        verbose "Aggiungo FreecsD al crontab"
+        echo "$fullcrontab" > "$tempdir/mycron"
+        echo "$linetoadd" >> "$tempdir/mycron"
+        crontab "$tempdir/mycron"
+        rm "$tempdir/mycron"
+    else
+        verbose "OK! FreecsD è già presente nel crontab"
     fi
 
     req_result=$(curl -s -o /dev/null -u $oscam_user:$oscam_pass -w "%{http_code}" --anyauth "http://$oscam_ip:$oscam_port/")
@@ -782,17 +652,9 @@ if [ ! -z $inizialization_flag ]; then
 else
 
     if [ ! -z $a_flag ]; then
-        case "$server_list" in
-	 u)
+        if [ ! -z "$(echo "$server_list" | grep "^u$")"  ]; then
             server_list=$server_list_unstable
-	 ;;
-	 i)
-           server_list="http://progettofreecs.altervista.org/download/freecsD/servers_internal"
-	 ;;
-	 t)
-            server_list="http://progettofreecs.altervista.org/download/freecsD/servers_tools"
-	 ;;
-	esac
+        fi
         new_servers $server_list
     fi
 
@@ -803,7 +665,7 @@ debug "tor_patch_flag $tor_patch_flag"
 
             if [ ! -z "$tor_patch_flag" ]; then
                  debug "Eseguo tor_patch_webifRequest"
-                 tor_patch_wbr
+                 tor_patch_wbr /tmp/clines-for-tor
             else
                  handle_servers
             fi
